### ISSUE TITLE
Корекции по Ти гласуваш

### ISSUE THREAD

**Issue by svilenzhelev** [ti-broish/public#21]
- [x] Да се добави "Не подкрепям никого"
- [x] Да се добави възможност за размаркиране на преференция. 
- [x] При избрана преференция, размаркиране на партия и маркиране на същата или нова партия, преференцията си остава. Да изчистваме преференцията. 
- [x] Неназован кандидат => Име на кандидат
- [x] НАРОДНИ ПРЕДСТАВИТЕЛИ => Избори за Народни представители 2021
- [x] Бутонът Гласувай да е неактивен, ако нямам избрана партия
- [x] ВМРО няма преференции. Да им добавим
- [x] Може ли да направим билета да изглежда на истинския? - https://drive.google.com/file/d/1DDsr8u8Xf7vrswK00p2fx9dhMn-bYq6t/view?usp=sharing
- [x] Изпуснали сме един екран след гласуване - https://drive.google.com/file/d/1P0aGvA30Zac3k1ihp9TCZ7ycXI_ERyHq/view?usp=sharing

**Comment by blagoslav-mihaylov** [comment]
Всички промени са готови
